# Personal info
user:
  name: "Walidoux"
  email: "ma.walidkorchi@icloud.com"
  continent: "Africa"
  country: "Morocco"
  city: "Casablanca"

# System info
system:
  name: "studio"

# Misc
log_level: 'all' # 'all' | 'steps' | 'nothing'
